management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: 'true'
  endpoint:
    shutdown:
      enabled: 'true'
    health:
      show-details: always
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  datasource:
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/department_db?useSSL=false
info:
  app:
    name: Spring Boot Rest Api
    version: 1.0.0
    description: this is restfull web service for backend
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://192.168.1.2:8761/eureka/
server:
  port: '7001'
